# MySQL Database config
spring.application.name=iems-backend
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/iems
spring.datasource.username=fatfrogdev
spring.datasource.password=spr.dme11

# JPA Configs

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# Mongo database config

# spring.data.mongodb.authentication-database=admin
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=iems
# spring.data.mongodb.uri=mongodb://localhost:27017/iems
spring.data.mongodb.username=fatfrogdev
spring.data.mongodb.password=spr.dme11

# Servlet upload files config

spring.servlet.multipart.max-file-size=128MB
spring.servlet.multipart.max-request-size=128MB
spring.servlet.multipart.enabled=true