spring:
  application:
    name: iems-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/iems
    username: postgres
    password:
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
springdoc:
  packages-to-scan: com.fatfrogdev.iemsbackend.controllers